site_name: ABISSMAL Docs
site_description: Automated Behavioral tracking by Integrating Sensors that Survey Movements Around a target Location
keywords: abissmal, tanismo, python, raspberrypi, gsvidaurre, lastralab, github, tracking, science, research, data, sensors, video, rfid, irbb, temperature
robots: index, follow
nav:
  - Home: index.md
  - Usage: abissmal.md
  - About: about.md
  - Open Source: opensource.md
theme: readthedocs
extra_css:
  - css/extra.css
