site_name: ABISSMAL Docs
site_description: Automated Behavioral tracking by Integrating Sensors that Survey Movements Around a target Location
site_url: https://lastralab.github.io/ABISSMAL/site/
repo_url: https://github.com/lastralab/ABISSMAL
repo_name: ABISSMAL
site_author: tanismo
copyright: '© tanismo'
edit_uri: blob/docs/docs
nav:
  - Getting Started:
    - Installation: index.md
    - Usage: abissmal.md
  - About ABISSMAL:
    - Project Overview: about.md
    - Github Collaboration: opensource.md
theme:
  name: readthedocs
  logo: img/abissmal.png
extra_css:
  - css/extra.css
plugins:
  - search:
      indexing: 'full'
